OTS/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
urlpatterns = [
    path("ots/",include("online_test.urls")),
    path("admin/", admin.site.urls),
]

online_test/urls.py
from django.urls import path
from online_test import views
app_name='user'
urlpatterns = [
    path("welcome",views.welcome,name='welcome'),
    path("signup",views.signup,name='signup'),
    path("store_user",views.store_user,name='store_user'),
    path("login",views.login,name='login'),
    path("homepage",views.homepage,name='homepage'),
    path("subject1",views.subject1,name='subject1'),
    path("subject2",views.subject2,name='subject2'),
    path("subject3",views.subject3,name='subject3'),
    path("result1",views.result1,name='result1'),
    path("result2",views.result2,name='result2'),
    path("result3",views.result3,name='result3'),
    path("profile/", views.profile, name="profile"),  # Ensure function name matches views.py
    path('ChatBot', views.ChatBot, name="ChatBot"),
    path("test_history",views.test_history,name='test_history'),
    path("logout",views.logout,name='logout'),
    path("aboutUs",views.aboutUs,name='aboutUs'),
]

online_test/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    username=models.CharField(primary_key=True,max_length=30)
    password=models.CharField(max_length=10,null=False)
    name=models.CharField(max_length=30,null=False)
    def __str__(self):
        return self.name
    
class Profile(models.Model):
    username = models.CharField(max_length=255, unique=True, default="default_user")
    father_name = models.CharField(max_length=255, default="Unknown")
    mother_name = models.CharField(max_length=255, default="Unknown")
    phone = models.CharField(max_length=15, default="0000000000")
    email = models.EmailField(unique=True)
    address = models.TextField()

    def __str__(self):
        return self.username.username  # Returns actual username

    
class Test_history(models.Model):
    test_id=models.BigAutoField(auto_created=True,primary_key=True)
    username=models.ForeignKey(User,on_delete=models.CASCADE)
    subject=models.CharField(max_length=25,default='')
    total=models.IntegerField()
    correct=models.IntegerField()
    wrong=models.IntegerField()
    percentage=models.IntegerField()

class Test_paper_subject1(models.Model):
    q_id=models.IntegerField(primary_key=True)
    ques=models.CharField(max_length=100)
    a=models.CharField(max_length=50)
    b=models.CharField(max_length=50)
    c=models.CharField(max_length=50)
    d=models.CharField(max_length=50)
    ans=models.CharField(max_length=2)
    def __str__(self):
        return self.ques
    
class Test_paper_subject2(models.Model):
    q_id=models.IntegerField(primary_key=True)
    ques=models.CharField(max_length=100)
    a=models.CharField(max_length=50)
    b=models.CharField(max_length=50)
    c=models.CharField(max_length=50)
    d=models.CharField(max_length=50)
    ans=models.CharField(max_length=2)
    def __str__(self):
        return self.ques
    
class Test_paper_subject3(models.Model):
    q_id=models.IntegerField(primary_key=True)
    ques=models.CharField(max_length=100)
    a=models.CharField(max_length=50)
    b=models.CharField(max_length=50)
    c=models.CharField(max_length=50)
    d=models.CharField(max_length=50)
    ans=models.CharField(max_length=2)
    def __str__(self):
        return self.ques
    
    

online_test/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse
from online_test.models import *
import google.generativeai as ai
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
import json
from .models import Profile
from django.views.decorators.csrf import csrf_exempt

from django.views.decorators.csrf import csrf_exempt #include this 
import random
def welcome(request):
    template=loader.get_template("welcome.html")
    res=template.render()
    return HttpResponse(res)

def signup(request):
    template=loader.get_template("signup.html")
    res=template.render()
    return HttpResponse(res)

@csrf_exempt
def store_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        name = request.POST.get('name')

        if User.objects.filter(username=username).exists():
            return render(request, "signup.html", {'msg': 'Username already taken. Try another.'})

        User.objects.create(username=username, password=password, name=name)
        return render(request, "login.html")

    return render(request, "signup.html", {'msg': 'Invalid request. First, signup.'})

    
@csrf_exempt
def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = User.objects.filter(username=username, password=password).first()
        if user:
            request.session['username'] = username
            user_data = User.objects.filter(username=username)
            profile_data = Profile.objects.filter(username=username)

            return render(request, "homepage.html", {'user_data': user_data, 'profile_data': profile_data})

        return render(request, "login.html", {'msg': 'Invalid credentials. Try again.'})

    return render(request, "login.html")


def homepage(request):
    if 'username' not in request.session:
        return render(request, "welcome.html")

    username = request.session.get('username')
    user_data = User.objects.filter(username=username)
    profile_data = Profile.objects.filter(username__username=username).first()


    return render(request, "homepage.html", {'user_data': user_data, 'profile_data': profile_data})


def profile(request):
    return render(request, 'profile.html')  # Ensure 'profile.html' exists in templates

def profile_view(request):
    username = request.session.get('username')
    if not username:
        return HttpResponse("Unauthorized", status=401)

    user = User.objects.get(username=username)
    profile, created = Profile.objects.get_or_create(username=user)

    return render(request, 'profile.html', {'profile': profile})



@csrf_exempt
def update_profile(request):
    if request.method == "POST":
        data = json.loads(request.body)

        # Fetch user profile (adjust this according to your database structure)
        username = request.session.get('username')
        if not username:
            return JsonResponse({"success": False, "error": "Unauthorized"}, status=401)

        user = User.objects.get(username=username)
        user_profile, created = Profile.objects.get_or_create(username=user)

        for field, value in data.items():
            setattr(user_profile, field, value)

        user_profile.save()

        return JsonResponse({"success": True, "updated_data": data})
  

        # Update the fields dynamically
        for field, value in data.items():
            setattr(user_profile, field, value)

        user_profile.save()  # Save changes

        return JsonResponse({"success": True, "updated_data": data})
    
    return JsonResponse({"success": False, "error": "Invalid request"})

def subject1(request):
    ques=Test_paper_subject1.objects.all()
    quse_list=list(ques)
    random.shuffle(quse_list)
    quse_list=quse_list[:4:1] ###### total questions can be customized
    context={
        'quse_list':quse_list
    }
    template=loader.get_template("subject1.html")
    res=template.render(context,request)
    return HttpResponse(res)

@csrf_exempt # include  this
def result1(request):
    if request.method=='POST':
        subject='DBMS'
        correct=0
        total=4
        for i in range(1,7,1): # traverse total number of questions
            if ('id'+str(i)) in request.POST.keys():  
                q_id=request.POST['id'+str(i)]
                ans=request.POST['option'+str(i)]
                ques=Test_paper_subject1.objects.filter(q_id=q_id)
                if(len(ques.filter(ans=ans))):
                    correct=correct+1
        wrong=total-correct
        percentage=(correct/total)*100
        username=request.session.get('username')
        history=Test_history()
        history.subject=subject
        history.username=User.objects.get(username=username)
        history.total=total
        history.correct=correct
        history.wrong=wrong
        history.percentage=percentage
        history.save()
        context={
            'total':total,
            'correct':correct,
            'wrong':wrong,
            'percentage':percentage
        }
        template=loader.get_template("result1.html")
        res=template.render(context,request)
        return HttpResponse(res)
    else:
        template=loader.get_template("welcome.html")
        res=template.render()
        return HttpResponse(res)
    
def subject2(request):
    ques=Test_paper_subject2.objects.all()
    quse_list=list(ques)
    random.shuffle(quse_list)
    quse_list=quse_list[:4:1] ###### total questions can be customized
    context={
        'quse_list':quse_list
    }
    template=loader.get_template("subject2.html")
    res=template.render(context,request)
    return HttpResponse(res)

@csrf_exempt # include  this
def result2(request):
    if request.method=='POST':
        subject='OS'
        correct=0
        total=4
        for i in range(1,7,1): # traverse total number of questions
            if ('id'+str(i)) in request.POST.keys():  
                q_id=request.POST['id'+str(i)]
                ans=request.POST['option'+str(i)]
                ques=Test_paper_subject2.objects.filter(q_id=q_id)
                if(len(ques.filter(ans=ans))):
                    correct=correct+1
        wrong=total-correct
        percentage=(correct/total)*100
        username=request.session.get('username')
        history=Test_history()
        history.username=User.objects.get(username=username)
        history.subject=subject
        history.total=total
        history.correct=correct
        history.wrong=wrong
        history.percentage=percentage
        history.save()
        context={
            'total':total,
            'correct':correct,
            'wrong':wrong,
            'percentage':percentage
        }
        template=loader.get_template("result2.html")
        res=template.render(context,request)
        return HttpResponse(res)
    else:
        template=loader.get_template("welcome.html")
        res=template.render()
        return HttpResponse(res)
    
def subject3(request):
    ques=Test_paper_subject3.objects.all()
    quse_list=list(ques)
    random.shuffle(quse_list)
    quse_list=quse_list[:4:1] ###### total questions can be customized
    context={
        'quse_list':quse_list
    }
    template=loader.get_template("subject3.html")
    res=template.render(context,request)
    return HttpResponse(res)

@csrf_exempt # include  this
def result3(request):
    if request.method=='POST':
        subject='CN'
        correct=0
        total=4 #total number of questions displayed on subject3.html
        for i in range(1,7,1): # traverse total number of questions
            if ('id'+str(i)) in request.POST.keys():  
                q_id=request.POST['id'+str(i)]
                ans=request.POST['option'+str(i)]
                ques=Test_paper_subject3.objects.filter(q_id=q_id)
                if(len(ques.filter(ans=ans))):
                    correct=correct+1
        wrong=total-correct
        percentage=(correct/total)*100
        username=request.session.get('username')
        history=Test_history()
        history.username=User.objects.get(username=username)
        history.subject=subject
        history.total=total
        history.correct=correct
        history.wrong=wrong
        history.percentage=percentage
        history.save()
        context={
            'total':total,
            'correct':correct,
            'wrong':wrong,
            'percentage':percentage
        }
        template=loader.get_template("result3.html")
        res=template.render(context,request)
        return HttpResponse(res)
    else:
        template=loader.get_template("welcome.html")
        res=template.render()
        return HttpResponse(res)

def test_history(request):
    username=request.session.get('username')
    history=Test_history.objects.filter(username=username)
    context={
        'history':history
    }
    template=loader.get_template("test_history.html")
    res=template.render(context,request)
    return HttpResponse(res)

def logout(request):
    del request.session['username'] #must destroy session keys
    template=loader.get_template("welcome.html")
    res=template.render()
    return HttpResponse(res)

def aboutUs(request):
    template=loader.get_template("about.html")
    res=template.render()
    return HttpResponse(res)


# API Key
API_KEY = 'Your API Key'

# Configure the Gemini API
ai.configure(api_key=API_KEY)

# Create a new model
model = ai.GenerativeModel("gemini-pro")
chat = model.start_chat()

# View to handle the chatbot interface
@csrf_exempt
def ChatBot(request):
    if request.method == "POST":
        user_input = request.POST.get('user_input')

        try:
            gemini_response = chat.send_message(user_input)

online_test/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login Page</title>
    <style>
      body {
        background: radial-gradient(circle, #2c3e50, #000);
        font-family: 'Poppins', sans-serif;
        margin: 0;
        padding: 0;
        color: #ffffff;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        overflow: auto;
      }

      .login-container {
        background: linear-gradient(135deg, rgba(76, 175, 80, 0.9), rgba(33, 150, 243, 0.9));
        background-size: cover;
        padding: 75px;
        border-radius: 15px;
        box-shadow: 0 15px 50px rgba(0, 0, 0, 0.3);
        width: 400px;
        font-size: larger;
        display: flex;
        flex-direction: column;
        align-items: center;
        position: relative;
        overflow: hidden;
      }

      .login-container::before {
        content: "";
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: rgba(0, 0, 0, 0.4);
        border-radius: 15px;
        z-index: -1;
      }

      h1 {
        text-align: center;
        color: #fff;
        font-size: 2.5em;
        margin-bottom: 20px;
        font-weight: bold;
        color: #ffffff;
        text-transform: uppercase;
      }

      label {
        display: block;
        margin: 10px 0 5px;
        color: #fff;
        font-size: 1.1em;
      }

      input {
        width: 100%;
        padding: 12px;
        margin-bottom: 20px;
        box-sizing: border-box;
        border: 1px solid #ccc;
        border-radius: 25px;
        font-size: 1.1em;
        transition: all 0.3s ease;
        background: rgba(255, 255, 255, 0.9);
      }

      input:focus {
        outline: none;
        border-color: #4caf50;
        box-shadow: 0 0 5px rgba(76, 175, 80, 0.8);
      }

      button {
        background-color: #4caf50;
        color: #fff;
        padding: 12px 20px;
        border: none;
        border-radius: 25px;
        cursor: pointer;
        width: 100%;
        font-size: 1.2em;
        transition: background-color 0.3s ease;
      }

      button:hover {
        background-color: #45a049;
      }

      .form-footer {
        margin-top: 20px;
        text-align: center;
        color: #fff;
        font-size: 1.1em;
      }

      .form-footer a {
        color: #4caf50;
        text-decoration: none;
        font-weight: bold;
      }

      .form-footer a:hover {
        color: #45a049;
      }

      /* Decorative Squares */
      .square {
        position: absolute;
        background: rgba(255, 255, 255, 0.08);
        box-shadow: 0 4px 15px rgba(255, 255, 255, 0.2);
        z-index: -1;
        animation: moveSquare 10s linear infinite;
      }

      .square:nth-child(1) {
        top: 20%;
        left: 10%;
        width: 100px;
        height: 100px;
        animation-duration: 15s;
      }

      .square:nth-child(2) {
        top: 40%;
        right: 15%;
        width: 80px;
        height: 80px;
        animation-duration: 12s;
      }

      .square:nth-child(3) {
        bottom: 10%;
        left: 20%;
        width: 120px;
        height: 120px;
        animation-duration: 18s;
      }

      .square:nth-child(4) {
        bottom: 30%;
        right: 25%;
        width: 90px;
        height: 90px;
        animation-duration: 14s;
      }

      .square:nth-child(5) {
        top: 5%;
        right: 5%;
        width: 70px;
        height: 70px;
        animation-duration: 10s;
      }

      .square:nth-child(6) {
        bottom: 15%;
        left: 5%;
        width: 50px;
        height: 50px;
        animation-duration: 8s;
      }

      /* Moving Squares Animation */
      @keyframes moveSquare {
        0% {
          transform: translate(0px, 0px) rotate(0deg);
        }
        50% {
          transform: translate(30px, -30px) rotate(45deg);
        }
        100% {
          transform: translate(0px, 0px) rotate(0deg);
        }
      }
    </style>
  </head>
  <body>
    <!-- Decorative Squares -->
    <div class="square"></div>
    <div class="square"></div>
    <div class="square"></div>
    <div class="square"></div>
    <div class="square"></div>
    <div class="square"></div>
    
    <div class="login-container">
      <h1>{{msg}}</h1>
      <h1>Login</h1>
      <form method="post" action="{% url 'user:login' %}">
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required />

        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required />

        <button type="submit">Login</button>
      </form>
      <div class="form-footer">
        <h6>Don't have an account?</h6>
        <a href="{% url 'user:signup' %}">Sign up</a>
      </div>
    </div>
  </body>
</html>

online_test/templates/result1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Result Page</title>
    <style>
        body {
            background-color: black;
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            color: #f0f0f0;
            overflow: hidden;
        }

        a {
            text-decoration: none;
            color: #ffffff;
            background-color: #4caf50;
            padding: 8px 15px;
            border-radius: 5px;
            font-size: 14px;
            transition: background-color 0.3s, transform 0.2s;
        }

        a:hover {
            background-color: #45a049;
            transform: scale(1.1);
        }

        .card {
            position: center;
            left: 50%;
            transform: translateX(-50%);
            top: 50px;
            background: linear-gradient(145deg, #8dcde9, #6bb8d9);
            border: 1px solid #5a9ac7;
            border-radius: 12px;
            padding: 20px;
            margin: 20px auto;
            width: 600px;
            box-shadow: 0 6px 30px rgba(0, 0, 0, 0.4);
            transition: transform 0.3s, box-shadow 0.3s;
            text-align: center;
        }

        .card:hover {
            transform: scale(1.05);
            box-shadow: 0 8px 40px rgba(0, 0, 0, 0.6);
        }

        .card1 {
            position: center;
            left: 50%;
            transform: translateX(-50%);
            top: 50px;
            background: linear-gradient(145deg, #95d488, #74ba6d);
            border: 1px solid #5b9459;
            border-radius: 12px;
            padding: 20px;
            margin: 20px auto;
            width: 600px;
            box-shadow: 0 6px 30px rgba(0, 0, 0, 0.4);
            transition: transform 0.3s, box-shadow 0.3s;
            text-align: center;
        }

        .card1:hover {
            transform: scale(1.05);
            box-shadow: 0 8px 40px rgba(0, 0, 0, 0.6);
        }

        h1 {
            margin: 10px 0;
            color: #fff;
        }

        b a {
            display: inline-block;
            margin: 10px 0;
        }

        /* Decorative Squares */
        .square {
            position: absolute;
            background: rgba(255, 255, 255, 0.08);
            box-shadow: 0 4px 15px rgba(255, 255, 255, 0.2);
            z-index: -1;
            animation: moveSquare 10s linear infinite;
        }

        .square:nth-child(1) {
            top: 20%;
            left: 10%;
            width: 100px;
            height: 100px;
            animation-duration: 15s;
        }

        .square:nth-child(2) {
            top: 40%;
            right: 15%;
            width: 80px;
            height: 80px;
            animation-duration: 12s;
        }

        .square:nth-child(3) {
            bottom: 10%;
            left: 20%;
            width: 120px;
            height: 120px;
            animation-duration: 18s;
        }

        .square:nth-child(4) {
            bottom: 30%;
            right: 25%;
            width: 90px;
            height: 90px;
            animation-duration: 14s;
        }

        .square:nth-child(5) {
            top: 5%;
            right: 5%;
            width: 70px;
            height: 70px;
            animation-duration: 10s;
        }

        .square:nth-child(6) {
            bottom: 15%;
            left: 5%;
            width: 50px;
            height: 50px;
            animation-duration: 8s;
        }

        /* Moving Squares Animation */
        @keyframes moveSquare {
            0% {
                transform: translate(0px, 0px) rotate(0deg);
            }
            50% {
                transform: translate(30px, -30px) rotate(45deg);
            }
            100% {
                transform: translate(0px, 0px) rotate(0deg);
            }
        }
    </style>
</head>
<body>
    <!-- Decorative Squares -->
    <div class="square"></div>
    <div class="square"></div>
    <div class="square"></div>
    <div class="square"></div>
    <div class="square"></div>
    <div class="square"></div>

    <div class="card">
        <h1>This is Result Page</h1>
        <h1>Total Number of Questions: {{total}}</h1>
        <h1>Total Number of Correct Attempts: {{correct}}</h1>
        <h1>Total Number of Wrong Attempts: {{wrong}}</h1>
        <h1>Result Percentage: {{percentage}}</h1>
    </div>
    <div class="card1">
        <b><a href="{% url 'user:homepage' %}">Go Back to Home Page</a></b><br><br>
        <b><a href="{% url 'user:logout' %}">Logout</a></b>
    </div>
</body>
</html>

online_test/templates/result2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Result Page</title>
    <style>
        body {
            background-color: black;
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            color: #f0f0f0;
            overflow: hidden;
        }

        a {
            text-decoration: none;
            color: #ffffff;
            background-color: #4caf50;
            padding: 8px 15px;
            border-radius: 5px;
            font-size: 14px;
            transition: background-color 0.3s, transform 0.2s;
        }

        a:hover {
            background-color: #45a049;
            transform: scale(1.1);
        }

        /* Card Styling */
        .card {
            position: relative;
            left: 50%;
            transform: translateX(-50%);
            top: 50px;
            background: linear-gradient(145deg, #8dcde9, #6bb8d9);
            border: 1px solid #5a9ac7;
            border-radius: 12px;
            padding: 20px;
            margin: 20px auto;
            width: 600px;
            box-shadow: 0 6px 30px rgba(0, 0, 0, 0.4);
            transition: transform 0.3s, box-shadow 0.3s;
            text-align: center;
        }

        .card:hover {
            transform: scale(1.05);
            box-shadow: 0 8px 40px rgba(0, 0, 0, 0.6);
        }

        h1 {
            margin: 10px 0;
            color: #fff;
        }

        h3 {
            margin: 10px 0;
            color: #e0e0e0;
        }

        /* Decorative Squares */
        .square {
            position: absolute;
            background: rgba(255, 255, 255, 0.08);
            box-shadow: 0 4px 15px rgba(255, 255, 255, 0.2);
            z-index: -1;
            animation: moveSquare 10s linear infinite;
        }

        .square:nth-child(1) {
            top: 20%;
            left: 10%;
            width: 100px;
            height: 100px;
            animation-duration: 15s;
        }

        .square:nth-child(2) {
            top: 40%;
            right: 15%;
            width: 80px;
            height: 80px;
            animation-duration: 12s;
        }

        .square:nth-child(3) {
            bottom: 10%;
            left: 20%;
            width: 120px;
            height: 120px;
            animation-duration: 18s;
        }

        .square:nth-child(4) {
            bottom: 30%;
            right: 25%;
            width: 90px;
            height: 90px;
            animation-duration: 14s;
        }

        .square:nth-child(5) {
            top: 5%;
            right: 5%;
            width: 70px;
            height: 70px;
            animation-duration: 10s;
        }

        .square:nth-child(6) {
            bottom: 15%;
            left: 5%;
            width: 50px;
            height: 50px;
            animation-duration: 8s;
        }

        /* Moving Squares Animation */
        @keyframes moveSquare {
            0% {
                transform: translate(0px, 0px) rotate(0deg);
            }
            50% {
                transform: translate(30px, -30px) rotate(45deg);
            }
            100% {
                transform: translate(0px, 0px) rotate(0deg);
            }
        }
    </style>
</head>
<body>
    <!-- Decorative Squares -->
    <div class="square"></div>
    <div class="square"></div>
    <div class="square"></div>
    <div class="square"></div>
    <div class="square"></div>
    <div class="square"></div>

    <!-- Result Card -->
    <div class="card">
        <h1>This is Result Page</h1>
        <h3>Total Number of Questions: {{total}}</h3>
        <h3>Total Number of Correct Attempts: {{correct}}</h3>
        <h3>Total Number of Wrong Attempts: {{wrong}}</h3>
        <h3>Result Percentage: {{percentage}}</h3>
    </div>

    <!-- Links -->
    <div class="card">
        <b><a href="{% url 'user:homepage' %}">Go Back to Home Page</a></b><br><br>
        <b><a href="{% url 'user:logout' %}">Logout</a></b>
    </div>
</body>
</html>

online_test/templates/result3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Result Page</title>
    <style>
        body {
            background-color: black;
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            color: #f0f0f0;
            overflow: hidden;
        }

        a {
            text-decoration: none;
            color: #ffffff;
            background-color: #4caf50;
            padding: 8px 15px;
            border-radius: 5px;
            font-size: 14px;
            transition: background-color 0.3s, transform 0.2s;
        }

        a:hover {
            background-color: #45a049;
            transform: scale(1.1);
        }

        /* Card Styling */
        .card {
            position: relative;
            left: 50%;
            transform: translateX(-50%);
            top: 50px;
            background: linear-gradient(145deg, #8dcde9, #6bb8d9);
            border: 1px solid #5a9ac7;
            border-radius: 12px;
            padding: 20px;
            margin: 20px auto;
            width: 600px;
            box-shadow: 0 6px 30px rgba(0, 0, 0, 0.4);
            transition: transform 0.3s, box-shadow 0.3s;
            text-align: center;
        }

        .card:hover {
            transform: scale(1.05);
            box-shadow: 0 8px 40px rgba(0, 0, 0, 0.6);
        }

        h1 {
            margin: 10px 0;
            color: #fff;
        }

        h3 {
            margin: 10px 0;
            color: #e0e0e0;
        }

        /* Decorative Squares */
        .square {
            position: absolute;
            background: rgba(255, 255, 255, 0.08);
            box-shadow: 0 4px 15px rgba(255, 255, 255, 0.2);
            z-index: -1;
            animation: moveSquare 10s linear infinite;
        }

        .square:nth-child(1) {
            top: 20%;
            left: 10%;
            width: 100px;
            height: 100px;
            animation-duration: 15s;
        }

        .square:nth-child(2) {
            top: 40%;
            right: 15%;
            width: 80px;
            height: 80px;
            animation-duration: 12s;
        }

        .square:nth-child(3) {
            bottom: 10%;
            left: 20%;
            width: 120px;
            height: 120px;
            animation-duration: 18s;
        }

        .square:nth-child(4) {
            bottom: 30%;
            right: 25%;
            width: 90px;
            height: 90px;
            animation-duration: 14s;
        }

        .square:nth-child(5) {
            top: 5%;
            right: 5%;
            width: 70px;
            height: 70px;
            animation-duration: 10s;
        }

        .square:nth-child(6) {
            bottom: 15%;
            left: 5%;
            width: 50px;
            height: 50px;
            animation-duration: 8s;
        }

        /* Moving Squares Animation */
        @keyframes moveSquare {
            0% {
                transform: translate(0px, 0px) rotate(0deg);
            }
            50% {
                transform: translate(30px, -30px) rotate(45deg);
            }
            100% {
                transform: translate(0px, 0px) rotate(0deg);
            }
        }
    </style>
</head>
<body>
    <!-- Decorative Squares -->
    <div class="square"></div>
    <div class="square"></div>
    <div class="square"></div>
    <div class="square"></div>
    <div class="square"></div>
    <div class="square"></div>

    <!-- Result Card -->
    <div class="card">
        <h1>This is Result Page</h1>
        <h3>Total Number of Questions: {{total}}</h3>
        <h3>Total Number of Correct Attempts: {{correct}}</h3>
        <h3>Total Number of Wrong Attempts: {{wrong}}</h3>
        <h3>Result Percentage: {{percentage}}</h3>
    </div>

    <!-- Links -->
    <div class="card">
        <b><a href="{% url 'user:homepage' %}">Go Back to Home Page</a></b><br><br>
        <b><a href="{% url 'user:logout' %}">Logout</a></b>
    </div>
</body>
</html>